require "ui.alpha"
require "ui.illuminate"
require "ui.colorscheme"
-- require "config.ui.conflict-marker"
-- require "config.ui.dressing"
-- require "config.ui.icons"
require "ui.neoscroll"
-- require "config.ui.nvim-webdev-icons"
-- require "config.ui.ts-context"
require "ui.notify"
